#!/usr/bin/env python
#
# Copyright 2011 Michael Diamond
# 
# This file is part of Abundant.
# 
# This software may be used and distributed according to the terms of
# the  GNU General Public License version 3 or any later version.
# See http://www.gnu.org/licenses/ for the full license text.

'''
Command line frontend to Abundant

@author: Michael Diamond
Created on Mar 14, 2011
'''

import os, sys

try:
    from abundant import abundant
except ImportError:
    sys.stderr.write("Could not find Abundant codebase in PYTHONPATH.  Bad install.")
    sys.exit(-1)
    
sys.exit(abundant.exec(sys.argv[1:],os.getcwd()))